// 100 JavaScript interview questions
const QUESTIONS = [
  "What is the difference between let, const and var in JavaScript?",
  "Explain hoisting in JavaScript.",
  "What are closures and why are they useful?",
  "What is the event loop in JavaScript?",
  "Explain the difference between synchronous and asynchronous code.",
  "What are Promises and how do they work?",
  "What is async/await and how does it relate to Promises?",
  "What is the difference between call, apply and bind?",
  "Explain prototypal inheritance in JavaScript.",
  "What is the difference between == and ===?",
  "Describe how 'this' works in JavaScript.",
  "What is functional programming and how is it applied in JS?",
  "What is a pure function?",
  "Explain immutability and why it matters.",
  "How do you implement inheritance in ES6 classes?",
  "What is the difference between Object.freeze and const?",
  "Explain the difference between map, filter and reduce.",
  "What is the rest operator and spread syntax?",
  "What are arrow functions and how do they handle 'this'?",
  "What is event delegation?",
  "Explain debouncing and throttling.",
  "How does JSON.stringify handle circular references?",
  "What is the difference between null and undefined?",
  "How does garbage collection work in JavaScript?",
  "What is a Symbol and when would you use it?",
  "Explain generators and yield.",
  "What is the difference between shallow and deep copy?",
  "How does Object.assign work?",
  "Explain the module pattern in JavaScript.",
  "What are IIFEs and why are they used?",
  "What is the Temporal Dead Zone (TDZ)?",
  "Explain how the spread operator works with arrays and objects.",
  "What is a Promise.all and Promise.race?",
  "How do you handle errors with async/await?",
  "What is memoization?",
  "Explain Currying in JavaScript.",
  "What is the Purpose of the 'new' keyword?",
  "Explain how private fields work in JS classes (#field).",
  "What is the difference between prototype and __proto__?",
  "What is the difference between instance method and static method?",
  "Explain the difference between for...in and for...of loops.",
  "What is the browser's rendering pipeline?",
  "How does CSSOM and DOM interact with JS reflows?",
  "Explain Cross-Origin Resource Sharing (CORS).",
  "What are service workers and how do they work?",
  "Explain how the fetch API works.",
  "What are web sockets and when to use them?",
  "Explain localStorage and sessionStorage differences.",
  "How do you optimize web performance in JS?",
  "What is tree-shaking and why is it important?",
  "Explain event bubbling and capturing.",
  "What are custom events and how do you dispatch them?",
  "What is the difference between map and WeakMap?",
  "Explain WeakSet and Set differences.",
  "How do you create a debounce function? (describe or code)",
  "What are Typed Arrays?",
  "Explain the purpose of requestAnimationFrame.",
  "How do you detect a memory leak in JS?",
  "Explain the concept of microtasks vs macrotasks.",
  "What is tail call optimization?",
  "Explain the difference between host objects and native objects.",
  "How do you create an iterator in JavaScript?",
  "What is the purpose of Reflect API?",
  "Explain Proxy and a use-case.",
  "What is the module resolution in Node.js?",
  "Explain event loop in Node.js vs browser.",
  "What are streams in Node.js?",
  "Describe how to handle file uploads in Node.js.",
  "What is the 'use strict' directive do?",
  "Explain the difference between synchronous and asynchronous file I/O in Node.",
  "How do you implement authentication in a Node.js app?",
  "What is CORS and how to configure it in Node/Express?",
  "Explain how to prevent XSS in web apps.",
  "What is Cross-Site Request Forgery (CSRF)?",
  "What are security best practices for JS applications?",
  "What is the difference between HTTP/1.1 and HTTP/2 from JS perspective?",
  "Explain WebAssembly and use-cases in web apps.",
  "Describe how to test JS code (unit/integration/ e2e).",
  "What is the purpose of a bundler (webpack/rollup/vite)?",
  "Explain code splitting.",
  "What are source maps?",
  "How does tree shaking work in bundlers?",
  "What is Hot Module Replacement (HMR)?",
  "What are the common patterns for state management in React?",
  "Explain virtual DOM and reconciliation.",
  "What are hooks in React and why are they useful?",
  "Explain useMemo and useCallback and when to use them.",
  "What is context in React and when to use it?",
  "Explain how to optimize performance in React apps.",
  "Describe SSR vs CSR vs SSG.",
  "What is hydration?",
  "How do you handle forms in React?",
  "What is reconciliation algorithm (React fiber)?",
  "Explain portals in React.",
  "What is the Context API's pitfalls?",
  "How to use refs safely in React?",
  "Explain controlled vs uncontrolled components.",
  "What is PropTypes and why might you use it?",
  "Explain error boundaries in React.",
  "What are Higher-Order Components (HOCs)?",
  "Describe Render Props.",
  "What is the purpose of React.StrictMode?"
];

export default QUESTIONS;
